baseURL = 'https://blog.chinesehabit.com/'
languageCode = 'en-us'
title = 'Chinese Habit'
theme = "beautifulhugo"
publishDir = "docs"
enableRobotsTXT = true
googleAnalytics = "G-RF2PV65GRP"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "每日学中文"
  mainSections = ["post","posts"]
  logo = "img/avatar.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  rootlink = "https://chinesehabit.com"
  dateFormat = "January 2, 2006"
  since = "2022"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true